spring.datasource.url=jdbc:postgresql://db.1xxvmmenymhnkgjrnyt.supabase.co:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=4mIebYM22LRLwa6i
spring.jpa.hibernate.ddl-auto=update